server:
  port: 7777
spring:
  main:
    banner-mode: off
  application:
    name: admin-service
  boot:
    admin:
      context-path: /admin
      client:
        username: user
        password: secret
        url: http://localhost:7777/admin

management:
  endpoints:
    web:
      exposure:
        include: "*"
